### ISSUE TITLE
"The file is missing, can it be completed?"

### ISSUE THREAD

**Issue by yfjelley** [liqtags/DexScreenerClient#1]
Traceback (most recent call last):
  File "E:\DexScreenerClient-main\get_newest_pairs.py", line 1, in <module>
    from consts import WS_NEWEST
  File "E:\DexScreenerClient-main\consts.py", line 1, in <module>
    from lino_secrets import SUPABASE_URL, SUPABASE_KEY, WS_TRENDING, WS_GAINERS, WS_NEWEST
ModuleNotFoundError: No module named 'lino_secrets'

**Comment by ElSeidy** [comment]
same issue here!

**Comment by deancarloz** [comment]
same here

**Comment by nkoech** [comment]
Same here

**Comment by liqtags** [comment]
They are my own websocket nodes and keys. create your own secrets file or read the README about premium version.
