### ISSUE TITLE
where can i find the description about the dexscreener websocket?

### ISSUE THREAD

**Issue by xyq-c-cpp** [liqtags/DexScreenerClient#10]
thanks so so much for your project, and I had saw your code, found the websocket use of dexscreener, but I don't find the description about websocket api on dexscreener api reference, I wanna get more message from that if you can tell me where i can find that description. finnally thanks again. @liqtags

**Comment by xyq-c-cpp** [comment]
I think I had found that. emmmm...use brower debug tool and then would find some detail information.  anyway thanks again. @liqtags

**Comment by liqtags** [comment]
> I think I had found that. emmmm...use brower debug tool and then would find some detail information.  anyway thanks again. @liqtags 

No problem 😎

**Comment by liqtags** [comment]
The websocket is sort of a black box and I was only able to reverse engineer from the frontend so far.
