### ISSUE TITLE
ModuleNotFoundError: No module named 'lino_secrets'

### ISSUE THREAD

**Issue by nnachefski** [liqtags/DexScreenerClient#5]
Can you please share an example of what the secrets file should look like?  With your secrets removed of course... :-)

```
from lino_secrets import SUPABASE_URL, SUPABASE_KEY, WS_TRENDING, WS_GAINERS, WS_NEWEST
ModuleNotFoundError: No module named 'lino_secrets'
```

**Comment by liqtags** [comment]
Hey @nnachefski, 

I use my own websocket nodes, soon I'll be making a V2 version that uses free websockets. please wait while I ship that.
