### ISSUE TITLE
Supabase Database - Missing Tables and Columns

### ISSUE THREAD

**Issue by DennyZen** [liqtags/DexScreenerClient#6]
Describe the issue
I attempted to run the project and connected it to a Supabase database. However, I encountered an issue where I could not save data to the database because the necessary tables and columns were not created. It appears that the database schema has not been set up.

Steps to reproduce
1. Clone the repository.
2. Set up the Supabase project and obtain the API key and URL.
3. Configure the project to use the Supabase database.
4. Attempt to run the project and save data.

Expected behavior
The necessary tables and columns should be created in the Supabase database, allowing data to be saved successfully.

Actual behavior
ErrorAPI   : {'code': '42P01', 'details': None, 'hint': None, 'message': 'relation "public.newest_pairs" does not exist'}
An error occurs indicating that the required tables and columns do not exist in the database.

**Comment by liqtags** [comment]
Create the tables in your supabase. I should add functionality to seed em, but I left that for you to do. just create db and tables needed or add flag to not add it.
