### ISSUE TITLE
Not working in vds

### ISSUE THREAD

**Issue by uicodee** [liqtags/DexScreenerClient#9]
Script working well in local computer but when I upload to server, script not working

`websocket._exceptions.WebSocketBadStatusException: Handshake status 403 Forbidden -+-+- {'date': 'Sun, 21 Jul 2024 05:12:09 GMT', 'content-type': 'text/html; charset=UTF-8', 'transfer-encoding': 'chunked', 'connection': 'keep-alive', 'x-frame-options': 'SAMEORIGIN', 'referrer-policy': 'same-origin', 'cache-control': 'max-age=15', 'expires': 'Sun, 21 Jul 2024 05:12:24 GMT', 'set-cookie': '__cf_bm=y4jqYashXgnZGWX784.vhLgMOaUZ.SxryCapqf_SXi8-1721538729-1.0.1.1-m2fTP8FXVMf8iTeoETxde5j4evdpwiVoAFDSQvRZ.rCJ.w82dbwolSFgfG2BGQU98_GO5FkBaylpmS1lNkSi8KkS7ylRwjp9nA3H5_KY_0I; path=/; expires=Sun, 21-Jul-24 05:42:09 GMT; domain=.dexscreener.com; HttpOnly; Secure; SameSite=None', 'server': 'cloudflare', 'cf-ray': '8a68b1c2c95f9ddf-DME', 'alt-svc': 'h3=":443"; ma=86400'} -+-+- None`

**Comment by liqtags** [comment]
Unsure why, will investigate it.

**Comment by liqtags** [comment]
Had no time to drive into this as in my environments it's working okay. running local on my NAS. If anyone wants to investigate the issue you can.

**Comment by liqtags** [comment]
This is because the websocket requires localhost connections or cloudflare cries about it.

**Comment by echograph** [comment]
I have the exact same problem but in local. Is that fixable?

**Comment by daniel-brzezicki** [comment]
I have the same issue, I am using python v10

**Comment by daniel-brzezicki** [comment]
any update on this?

**Comment by liqtags** [comment]
> I have the exact same problem but in local. Is that fixable?

Can you give details? I tried it today was working fine.
